spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PAS}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      instance: ${spring.application.name}
    enable:
      jvm: true
      process: true
      tomcat: true
      system: true
      logback: true
    distribution:
      slo:
        http.server.requests: 50ms
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.99
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
